### ISSUE TITLE
可以问任何事情呀

### ISSUE THREAD

**Issue by imtaotao** [kaili-yang/kaili-yang#1]
那能不能认识下，比较好奇国外的程序员生活

**Comment by kaili-yang** [comment]
> 那能不能认识下，比较好奇国外的程序员生活

总体来说生活是很舒适的，可能因为我单身，养活自己就行了，自己工资自己花，也没想过赚什么大钱，做好财务规划每个月定存点钱，做一些长期低风险指数基金定投。平时下了班想干什么干什么，国外人少地方大，住的地方风景就好，喜欢去海边看日落看海鸥发呆，但那样太晒了我怕晒黑现在喜欢去山里徒步玩水之类的（海边和山都在开车半小时车程内），好久不见人了以后呢就会觉得生活无聊，又开始找华人social，国外生活治好了我的社交恐惧症焦虑症强迫症。这里的人不会judge你，不会对你评头论足，没有身材焦虑容貌焦虑，只要自己舒服就好了。公司里老板也基本是结果导向，按时交付成果就行了，平时不会管你在干什么，不会干涉你的自由。海外求职是不会问性别年龄是否结婚生育这些问题的，这属于个人隐私。刚出国的第一年我报复性睡觉，每天睡到自然醒起来吃午饭，吃完饭溜一圈呼吸大自然的空气然后睡午觉，下午随便干什么晚上早点睡，这样修养了大半年才摆脱了国内那种疲劳感。现在每天精神都很好，不存在精神疲劳和肉体疲劳，甚至因为精神太好觉得生活有点无聊，开始学习一些兴趣爱好和极限户外运动，身体和精神状态也好了不少，也学习了很多新技能，动手能力也变强了很多。以上是我个人的体验，希望对你有帮助。

**Comment by imtaotao** [comment]
羡慕哭了，想出去的话，英语水平到什么地步大概可行呀

**Comment by dierbei** [comment]
我一直有个问题，就算我考不上 MIT，但是我能进去参观吗？

要是能够进去蹭节课，那就太帅了。

**Comment by kaili-yang** [comment]
> 羡慕哭了，想出去的话，英语水平到什么地步大概可行呀

现在大环境不好，办公室也开始卷了，想要混得好对英语听力和口语水平还是挺高的，因为需要在同事和老板面前表现自己，但如果普通混一混的话只要代码能力够强就行，英语差点也没事的。

**Comment by kaili-yang** [comment]
> 我一直有个问题，就算我考不上 MIT，但是我能进去参观吗？
> 
> 要是能够进去蹭节课，那就太帅了。

当然可以啦，高校都是开放的不是封闭的，任何时候都可以进去，但是蹭课的话最好找个好点的理由，不要被发现哈
